/robot1_ns:
  collision_monitor:
    ros__parameters:
      use_sim_time: True
      base_frame_id: "base_link"
      odom_frame_id: "odom"
      cmd_vel_in_topic: "/robot1_ns/cmd_vel_smoothed"
      cmd_vel_out_topic: "/robot1_ns/cmd_vel"
      state_topic: "/robot1_ns/collision_monitor_state"
      transform_tolerance: 0.2
      source_timeout: 1.0
      base_shift_correction: True
      stop_pub_timeout: 2.0
      polygons: ["FootprintApproach"]
      FootprintApproach:
        type: "polygon"
        action_type: "approach"
        footprint_topic: "/robot1_ns/local_costmap/published_footprint"
        time_before_collision: 2.0
        simulation_time_step: 0.1
        min_points: 6
        visualize: False
        enabled: True
      observation_sources: ["scan"]
      scan:
        type: "scan"
        topic: "/robot1_ns/scan"
        min_height: 0.15
        max_height: 2.0
        enabled: True