# Namespace: /robot1/slam_toolbox
robot1_slam_toolbox:
  ros__parameters:
    use_sim_time: True
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan
    mode: online_async
    resolution: 0.05
    max_laser_range: 30.0
    minimum_time_interval: 1

    # SLAM ToolBox parameters
    map_file_name: /tmp/map
    enable_interactive_mode: False
    publish_to_viz: True
    update_map_only: False
    laser_scan_topic: scan
    maximum_laser_line_length: 0.02

    # Solver parameters
    solver_plugins: ["libspa_solver_plugin.so"]

    # More parameters can be added as required by the SLAM Toolbox

# Namespace: /robot2/slam_toolbox
robot2_slam_toolbox:
  ros__parameters:
    use_sim_time: True
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan
    mode: online_async
    resolution: 0.05
    max_laser_range: 30.0
    minimum_time_interval: 1

    # SLAM ToolBox parameters
    map_file_name: /tmp/map
    enable_interactive_mode: False
    publish_to_viz: True
    update_map_only: False
    laser_scan_topic: scan
    maximum_laser_line_length: 0.02

    # Solver parameters
    solver_plugins: ["libspa_solver_plugin.so"]

    # More parameters can be added as required by the SLAM Toolbox