amcl:
  ros__parameters:
    use_sim_time: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "ros2_ws/src/disaster_response_swarm/maps/map.yaml"

world_model:
  ros__parameters:
    use_sim_time: true

dwb_controller:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true